# Generated by Django 4.1.7 on 2023-04-05 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_menuitem_rename_date_created_order_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_number', models.IntegerField()),
                ('customer_name', models.CharField(max_length=50)),
                ('is_booked', models.BooleanField(default=False)),
                ('is_order_placed', models.BooleanField(default=False)),
            ],
        ),
    ]
